# Generated by Django 4.2.16 on 2024-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('accountno', models.IntegerField(primary_key='accountno', serialize=False)),
                ('dob', models.DateField()),
                ('aadharno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=21)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
